### PR TITLE
Dummy PR to test CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Okay, looks like CI is running now.

@Wimmerer @amontoison

**Comment by amontoison** [comment]
Builds of CirrusCI are missing. Is it enable for the `JuliaSparse` organization?

**Comment by DilumAluthge** [comment]
I'll do that now.

**Comment by DilumAluthge** [comment]
Okay, the `Cirrus CI` GitHub app is now installed on the `JuliaSparse` GitHub organization.

**Comment by amontoison** [comment]
Thanks, can you also update the `.cirrus.yml` to use this [one](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/.cirrus.yml)?
With the help of Mosè and Elliot, we also test Apple M1 with it.

**Pull request closed without merging**
