### PR TITLE
modernize package for Julia 1.0+

### PR DESCRIPTION
**Pull request by bicycle1885**
I think we no longer need to support Julia 0.7 or earlier. So, this pull request updates the package for Julia 1.0 world, which also suppresses some noisy warnings.

### CODE REVIEW

**Comment by tkonolige** [comment]
I'd like to maintain compatibility with older versions of Julia if possible. Can you do that?

**Comment by bicycle1885** [comment]
Technically, I can, but I'm a little bit reluctant to do that because I need to set up an old Julia installation. Why do you think it is better to maintain compatibility? People who still use Julia 0.6 and 0.7 can use older releases of this package. Julia 0.7 and earlier are no longer maintained and thus I think it is not reasonable to maintain packages for them.

**Comment by tkonolige** [comment]
This package works as is right now with old and new versions of julia. I don't see a reason to unnecessarily drop support.

**Comment by yuehhua** [comment]
Could someone merge this? `using Compat.SparseArrays` really blocks this package moving forward to new versions.

**Comment by tkonolige** [comment]
Closed in favor of #45. That PR is built off this one though. Thanks @bicycle1885!

**Pull request closed without merging**
