### PR TITLE
Modernize package and update CI

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by tkonolige** [comment]
Thanks @amontoison! Could you remove `CompatHelper` and `TagBot` from this PR and add them in a new PR? I don't have permissions to generate an ssh key for them. Could you also add testing for 1.8.

**Comment by amontoison** [comment]
> Thanks @amontoison! Could you remove `CompatHelper` and `TagBot` from this PR and add them in a new PR? I don't have permissions to generate an ssh key for them. Could you also add testing for 1.8.

`1` means the last release of Julia (1.8.3) for information in `ci.yml`.
I open a different PR for CI scripts.

**Comment by amontoison** [comment]
> Thanks @amontoison! Could you remove `CompatHelper` and `TagBot` from this PR and add them in a new PR? I don't have permissions to generate an ssh key for them. Could you also add testing for 1.8.

I will ask on Slack if someone can generate an ssh key.

**Comment by Wimmerer** [comment]
I should have just added the keys, let me know if there are any issues. Once everything is set up I can also put the docs on the JuliaSparse domain.

**Comment by amontoison** [comment]
Thanks Will !
Can you verify that GitHub Actions are activated in the settings?
I don't see any build in #45.
I will also a `docs` folder tomorrow for the documentation.

**Comment by Wimmerer** [comment]
Not sure why it's not running yet either :/, I'll investigate more in the morning as well.

**Pull request merged**
